---
title: "Integrating raster data into spatial databases"
author: "Matt Williamson"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Your assignment

The goals for this assignment are to:

- build your experience using functions to run calculations on rasters
- give you practice summarizing raster datasets for inclusion in analysis databases
- demonstrate the use of benchmarking to help scale analyses

_By the end of the assignment_ you should have an `sf` object that contains all of the Gap Status 1 protected areas (PA) in our region along with the median income of the counties within 100km of each PA, the housing value within that same region, mammalian species richness, ecosystem productivity (as assessed by NDVI). Insert your code chunks beneath each step.

# Step 1: Load your libraries and the data
Navigate to this week's data folder (`/opt/data/session16/`) and use `list.files()` to see the data contained therein. You should see the regional PA shapefile from last week (`reg_pas.shp`), along with rasters for mammalian richness (`mammal_rich.tif`; from [Clinton Jenkins' global biodiversity dataset](https://biodiversitymapping.org/index.php/download/)), land value (`regval.tif`) from the Nolte dataset, and a MODIS scene for the region (`modis.tif`). Load each into your workspace by assigning it to an object. Check the CRS and reproject where necessary,


# Step 2: Filter the data
You'll need to filter the PADUS dataset so that it only contains the [Gap Status 1](https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis/gap/science/pad-us-data-overview?qt-science_center_objects=0#qt-science_center_objects) protected areas. Check out the link to learn more about the different protection statuses. 


# Step 3: Get the data for median income by county
Follow the example to use the `tidycensus` package to download median income by county (along with its geometry).

# Step 4: Use a spatial join
Use `st_join` to connect your PAs dataset with every county within 100km and then use `group_by` and `summarise` to take the mean value of the median income data for each PA. By the time you are done with this step you should have the same number of rows that you had after your initial filter of the PAs (step 2).

# Step 5: Buffer your PAs
In order to get the raster data from the same area that you just estimated median income, you'll need to buffer the PAs by 100km

# Step 6: Crop all of the rasters to the extent of your buffered PA dataset
Before you start doing a bunch of raster processing you'll want to get rid of the parts you don't need. Do that here. Remember you'll want all of your rasters to have the same CRS.

# Step 7: Estimate NDVI
Now we are going to calculate the NDVI across the region. NDVI is the ratio of the (Near Infrared (NIR) band - the Red band)/(NIR band + the Red band) obtained from a variety of different satellites. You can think of it as an estimate of 'greeness' or productivity across the landscape (though it's ability to capture that varies by ecoregion). Here, we are using data from the MODIS satellite platform and the NIR band is the 2nd band and the Red band is the first. Write a function to calculate NDVI and then apply it to the MODIS data.

# Step 8: Extract the data
Now that you've got all the data together, it's time to run the extraction. Remember that extractions run faster when all of the layers are "stacked", but that requires you to use `resample` to get to the same origins and extents. Use `zonal` to estimate the `mean` and `sd` for each of the mammalian richness, land value, and NDVI datasets. Then use `extract` (without specifying a function) to estimate the same thig. Use `system.time()` to bencmark each approach.

# Step 9: Join back to your PA dataset
Now that you have the raster data extracted and summarized (into the mean and standard deviation) for each buffered PA, you should be able to join it back to the dataset you created in steps 2-4. Do that here.

__Question 1:__ Which PA is the most productive in terms of NDVI?
__Question 2:__ Which PA has the lowest mammalian species richess?
__Question 3:__ Which PA is in the county with the highest ratio of land cost to median income (i.e. where is land cost the highest and income the lowest)?
__Question 4:__ Which is faster, using `zonal` twice or `extract` once?

